name: Java CI/CD Pipeline to Tomcat

on:
  push:
    branches: [ main ]   # Trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Build with Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4. Upload WAR as artifact (optional, for later jobs)
      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp
          path: target/*.war

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
      # 5. Download WAR artifact
      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: myapp

      # 6. Deploy WAR via Tomcat Manager
      - name: Deploy to Tomcat
        run: |
          WAR_FILE=$(ls *.war)
          echo "Deploying $WAR_FILE to Tomcat..."
          curl -v --upload-file "$WAR_FILE" \
            "http://${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }}@${{ secrets.TOMCAT_HOST }}/manager/text/deploy?path=/myapp&update=true"
